repository:
  sections:
    - title: "Code of Conduct"
      icon: "code-of-conduct"
      link: "CODE_OF_CONDUCT.md"
    - title: "Security"
      icon: "law"
      link: "SECURITY.md"
    - title: "Troubleshooting"
      icon: "tools"
      link: "TROUBLESHOOTING.md"
